runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /tasks/.*
  script: server.main2.app
  login: admin

- url: /admin/.*
  script: server.main2.app
  login: admin
  
- url: /api/.*
  script: server.main2.app

- url: (.*)/
  static_files: src/index.html
  upload: src/index.html

- url: /src
  static_dir: src/

libraries:
- name: ssl
  version: latest
- name: pytz
  version: "2017.3"

skip_files:
- node_modules/
- server/tests
- .gitignore
- \.git/
- gulpfile.js
- package.json
- package-lock.json
- angular.json
- README.md