runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /tasks/.*
  script: server.main.app
  login: admin
  
- url: /api/.*
  script: server.main.app

- url: (.*)/
  static_files: src/index.html
  upload: src/index.html

- url: /src
  static_dir: src/

libraries:
- name: ssl
  version: latest